name: concoin
description: A flutter coin flipping app for sore losers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.0
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3

flutter_native_splash:
  color : "#2196f3"
  image : assets/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

